<img src='img/1_numpy.png' width=50 style='float:left'>

# NumPy

In [1]:
import numpy as np

## array에 적용되는 다양한 함수

### 하나의 array에 적용되는 함수

**random.randn(d0,d1,.., dn) : 표준정규난수 생성**

: https://numpy.org/doc/stable/reference/random/legacy.html

In [10]:
arr1=np.random.randn(10)
arr1

array([ 0.97674917,  0.09359954,  1.64106689, -0.54651104, -0.52735349,
        0.89596277, -1.68724437,  1.77170545,  0.20612814,  0.88145343])

In [11]:
arr2=np.random.randn(3,5)
arr2

array([[ 2.13835869, -0.09608841,  1.0342861 , -0.36749656,  2.01613947],
       [-0.0724767 , -2.14425656, -0.14454689, -1.0235894 , -0.41110556],
       [-1.55153254,  0.73072669, -0.49411814, -0.99166136,  0.91211799]])

In [6]:
np.random.random(5)

array([0.73118912, 0.95449059, 0.21479765, 0.21282595, 0.07875668])

**수학 관련 함수**

- 제곱근, 절대값, 삼각함수, 지수로그함수, 반올림함수 등

https://numpy.org/doc/stable/reference/routines.math.html

In [9]:
np.abs(arr1)

array([1.69806941, 0.62914792, 0.07104491, 0.36602257, 0.83974889,
       0.03071574, 0.84770468, 0.04153087, 0.682218  , 0.3101791 ])

In [12]:
np.sqrt(np.abs(arr2))

array([[1.46231279, 0.3099813 , 1.01699858, 0.60621494, 1.41990826],
       [0.26921498, 1.46432802, 0.38019323, 1.01172595, 0.64117514],
       [1.24560529, 0.85482553, 0.70293537, 0.99582195, 0.95504868]])

In [13]:
np.square(arr2)

array([[4.57257788, 0.00923298, 1.06974774, 0.13505372, 4.06481836],
       [0.00525287, 4.59783621, 0.0208938 , 1.04773527, 0.16900778],
       [2.40725321, 0.5339615 , 0.24415273, 0.98339224, 0.83195922]])

**지수함수**

In [14]:
np.exp(arr1)

array([2.65580861, 1.09811991, 5.16067247, 0.57896628, 0.59016478,
       2.44969315, 0.18502869, 5.88087432, 1.22891066, 2.41440632])

**로그함수**

- 자연로그 : log()
- 상용로그 : log10()
- 밑이2인 로그 : log2()

In [15]:
np.log(np.abs(arr1))

array([-0.0235254 , -2.36872976,  0.49534658, -0.60420077, -0.6398842 ,
       -0.10985642,  0.52309665,  0.57194261, -1.57925727, -0.12618311])

In [16]:
np.log10(np.abs(arr1))

array([-0.01021695, -1.02872626,  0.21512628, -0.26240106, -0.27789818,
       -0.04771004,  0.22717799,  0.24839152, -0.68586272, -0.05480063])

In [17]:
np.log2(np.abs(arr1))

array([-0.03393997, -3.41735468,  0.71463405, -0.87167745, -0.92315777,
       -0.15848931,  0.75466894,  0.82513877, -2.27838663, -0.18204375])

**각 성분의 부호 계산 : sign()**

: +인 경우 1, -인 경우 -1, 0인 경우 0

In [18]:
arr1

array([ 0.97674917,  0.09359954,  1.64106689, -0.54651104, -0.52735349,
        0.89596277, -1.68724437,  1.77170545,  0.20612814,  0.88145343])

In [19]:
np.sign(arr1)

array([ 1.,  1.,  1., -1., -1.,  1., -1.,  1.,  1.,  1.])

**반올림 함수**

In [20]:
np.floor(arr1)

array([ 0.,  0.,  1., -1., -1.,  0., -2.,  1.,  0.,  0.])

In [21]:
np.ceil(arr1)

array([ 1.,  1.,  2., -0., -0.,  1., -1.,  2.,  1.,  1.])

In [22]:
np.fix(arr1)

array([ 0.,  0.,  1., -0., -0.,  0., -1.,  1.,  0.,  0.])

**NaN 여부 확인**

In [23]:
np.nan

nan

In [24]:
arr2[2,3]=np.nan
arr2

array([[ 2.13835869, -0.09608841,  1.0342861 , -0.36749656,  2.01613947],
       [-0.0724767 , -2.14425656, -0.14454689, -1.0235894 , -0.41110556],
       [-1.55153254,  0.73072669, -0.49411814,         nan,  0.91211799]])

In [25]:
np.isnan(arr2)

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False,  True, False]])

**무한대(inf) 확인**

In [26]:
np.inf

inf

In [27]:
np.isinf(arr2)

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

**삼각함수**

: 각 성분에 대해 삼각함수 값을 계산하기(cos, cosh, sin, sinh, tan, tanh)

In [28]:
np.cos(arr1)

array([ 0.55971941,  0.99562276, -0.07021275,  0.85434296,  0.86414195,
        0.62476736, -0.11618505, -0.19956024,  0.97883071,  0.63603026])

In [29]:
np.sin(arr1)

array([ 0.8286822 ,  0.09346294,  0.99753204, -0.51970963, -0.50324814,
        0.78081095, -0.99322758,  0.97988556,  0.20467155,  0.77166412])

**Sum, product, difference함수**

In [30]:
arr3=np.random.randn(3,4)
arr3

In [31]:
np.sum(arr3)

6.45410840175723

In [32]:
np.sum(arr3,axis=0)

array([ 3.27448262,  2.12885881,  1.50123266, -0.45046569])

In [33]:
np.sum(arr3,axis=1)

array([1.42227719, 0.33357556, 4.69825566])

**평균(mean), 표준편차(std), 분산(var)**

In [34]:
np.mean(arr3)

0.5378423668131025

In [35]:
np.mean(arr3,axis=1)

array([0.3555693 , 0.08339389, 1.17456391])

In [36]:
np.std(arr3)

0.8321928965631497

In [37]:
np.var(arr3,axis=0)

array([0.27037428, 1.00535198, 0.07723517, 0.60643905])

**최대값(max), 최소값(min)**

In [39]:
np.max(arr3,axis=1)

array([1.76783547, 0.71227713, 2.07222839])

**최대값, 최소값 위치 인덱스 : argmax(), argmin()**

In [40]:
np.argmax(arr3,axis=1)

array([0, 2, 1], dtype=int64)

In [41]:
np.argmin(arr3,axis=0)

array([1, 1, 0, 0], dtype=int64)

**누적합(cumsum), 누적곱(cumprod)**

In [42]:
np.cumsum(arr1)

array([0.97674917, 1.07034871, 2.71141561, 2.16490457, 1.63755108,
       2.53351385, 0.84626948, 2.61797492, 2.82410306, 3.70555649])

In [43]:
np.cumsum(arr3,axis=1)

array([[1.76783547, 2.13600496, 2.24379949, 1.42227719],
       [0.50335698, 0.1918179 , 0.90409504, 0.33357556],
       [1.00329017, 3.07551857, 3.75667956, 4.69825566]])

In [44]:
np.cumprod(arr1)

array([ 0.97674917,  0.09142328,  0.15003171, -0.08199399,  0.04323982,
        0.03874127, -0.06536598, -0.11580927, -0.02387155, -0.02104166])

In [45]:
np.cumprod(arr3,axis=1)

array([[ 1.76783547,  0.65086309,  0.07015948, -0.05763758],
       [ 0.50335698, -0.15681537, -0.111696  ,  0.06372475],
       [ 1.00329017,  2.07904638,  1.4161653 ,  1.3334274 ]])

### 정렬함수:sort(),argsort()

In [46]:
np.sort(arr1)

array([-1.68724437, -0.54651104, -0.52735349,  0.09359954,  0.20612814,
        0.88145343,  0.89596277,  0.97674917,  1.64106689,  1.77170545])

In [47]:
np.argsort(arr1)

array([6, 3, 4, 1, 8, 9, 5, 0, 2, 7], dtype=int64)

### 두 개의 array에 적용되는 함수

In [48]:
arr3

array([[ 1.76783547,  0.36816949,  0.10779453, -0.8215223 ],
       [ 0.50335698, -0.31153908,  0.71227713, -0.57051948],
       [ 1.00329017,  2.07222839,  0.68116099,  0.9415761 ]])

In [49]:
arr4=np.random.randn(3,4)
arr4

array([[-1.09183058e+00, -1.94306334e+00,  8.12315430e-01,
        -6.06268571e-01],
       [-1.71436344e-01, -1.16200687e-01,  2.20509910e-01,
         4.60496969e-01],
       [-1.04703373e-01,  1.05985300e-03,  1.39040637e+00,
        -6.05255486e-01]])

**두 개의 array에 대해 동일한 위치의 성분끼리 연산**

- add(), subtract(), multiply(), divide()

In [50]:
np.add(arr3,arr4)

array([[ 0.67600489, -1.57489384,  0.92010996, -1.42779088],
       [ 0.33192064, -0.42773977,  0.93278705, -0.11002251],
       [ 0.8985868 ,  2.07328824,  2.07156736,  0.33632061]])

In [51]:
np.divide(arr3,arr4)

array([[-1.61914816e+00, -1.89478895e-01,  1.32700341e-01,
         1.35504683e+00],
       [-2.93611594e+00,  2.68104335e+00,  3.23013661e+00,
        -1.23892126e+00],
       [-9.58221445e+00,  1.95520359e+03,  4.89900655e-01,
        -1.55566718e+00]])

- 최대값 또는 최소값 계산
: maximum(), minimum()

In [52]:
np.maximum(arr3,arr4)

array([[ 1.76783547,  0.36816949,  0.81231543, -0.60626857],
       [ 0.50335698, -0.11620069,  0.71227713,  0.46049697],
       [ 1.00329017,  2.07222839,  1.39040637,  0.9415761 ]])

---------------------------