## Numpy 연습문제2

In [6]:
import numpy as np

#### 1. 값 20~49를 갖는 벡터 x  생성하기

In [7]:
x=np.arange(20,50)
x

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

#### 2. 1번에서 생성한 벡터 요소를 역순으로 갖는 벡터 출력하기 

In [8]:
x[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20])

#### 3. 다음의 코드의 실행 결과를 예상해보기

**1)**

0 * np.nan

nan

**2)**

np.nan == np.nan

False

**3)**

np.nan - np.nan

nan

**4)**

np.inf > np.nan

False

**5)**

np.nan in set([np.nan])

True

#### 4. 모두 1의 요소를 갖는 5X3 크기 행렬 A와 3X2 크기 행렬 B 생성하기

In [18]:
A=np.ones((5,3))
B=np.ones((3,2))
print(A)
print(B)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


#### 5. 4번에서 생성한 두 행렬의 곱(dot)을 한 결과는?

In [19]:
A.dot(B)

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 6. 다음의 결과를 예상하시오.

**1)**

np.array(0) / np.array(0)

nan

**2)**

np.array(0) // np.array(0)

0

**3)**

np.array([np.nan]).astype(int).astype(float)

0

#### 7. 1번에서 생성한 벡터에서 30에서 38사이의 모든 요소 가져오기

In [17]:
mask=(x>=30)&(x<=38)
x[mask]

array([30, 31, 32, 33, 34, 35, 36, 37, 38])

#### 8. 크기 10의 실수 랜덤 벡터를 생성하고, 최대값을 0으로 변경하기

In [25]:
x=np.random.randn(10)
print(x)
x[x.argmax()]=0
x

[ 0.39152772 -0.95487659  0.89821487 -0.23352529 -0.09735657 -0.74145486
  0.89818466 -0.56161984  0.41363476  0.868554  ]


array([ 0.39152772, -0.95487659,  0.        , -0.23352529, -0.09735657,
       -0.74145486,  0.89818466, -0.56161984,  0.41363476,  0.868554  ])

#### 9. 1에서 10사이의 실수를 등간격으로 50개 갖는 벡터를 생성하되 32비트 실수로 생성하기

In [30]:
a=np.linspace(1,10,50,dtype='float32')
a

array([ 1.       ,  1.1836735,  1.3673469,  1.5510204,  1.7346939,
        1.9183674,  2.1020408,  2.2857144,  2.4693878,  2.6530612,
        2.8367348,  3.0204082,  3.2040815,  3.3877552,  3.5714285,
        3.7551022,  3.9387755,  4.122449 ,  4.3061223,  4.4897957,
        4.6734695,  4.857143 ,  5.0408163,  5.2244897,  5.408163 ,
        5.591837 ,  5.7755103,  5.9591837,  6.142857 ,  6.3265305,
        6.5102043,  6.6938777,  6.877551 ,  7.0612245,  7.244898 ,
        7.428571 ,  7.612245 ,  7.7959185,  7.979592 ,  8.163265 ,
        8.346939 ,  8.530612 ,  8.714286 ,  8.897959 ,  9.081633 ,
        9.265306 ,  9.448979 ,  9.632653 ,  9.816326 , 10.       ],
      dtype=float32)

#### 10. 9번에서 생성한 벡터를 32비트 정수형으로 변환하기

In [32]:
a_num=a.astype('int32')

In [33]:
a_num

array([ 1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  3,  3,  3,  3,  3,  3,
        4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  5,  6,  6,  6,  6,  6,  7,
        7,  7,  7,  7,  7,  8,  8,  8,  8,  8,  9,  9,  9,  9,  9, 10])

#### 11. 2022년 12월에 해당하는 모든 날짜를 갖는 벡터 생성하기

- 힌트 : arange()함수 사용하되 데이터 유형을 'datetime64[D]'로 지정할 것

In [71]:
date=np.arange('2022-12-01','2022-12-31',dtype='datetime64[D]')
date

array(['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04',
       '2022-12-05', '2022-12-06', '2022-12-07', '2022-12-08',
       '2022-12-09', '2022-12-10', '2022-12-11', '2022-12-12',
       '2022-12-13', '2022-12-14', '2022-12-15', '2022-12-16',
       '2022-12-17', '2022-12-18', '2022-12-19', '2022-12-20',
       '2022-12-21', '2022-12-22', '2022-12-23', '2022-12-24',
       '2022-12-25', '2022-12-26', '2022-12-27', '2022-12-28',
       '2022-12-29', '2022-12-30'], dtype='datetime64[D]')

#### 12. 오늘의 날짜를 생성하고, 어제, 내일의 날짜 생성해보기
- 힌트 : np.datetime64('today'), np.timedelta64() 사용

In [50]:
np.datetime64('today')

numpy.datetime64('2023-02-15')

In [51]:
np.datetime64('today')-1

numpy.datetime64('2023-02-14')

In [52]:
np.datetime64('today')+1

numpy.datetime64('2023-02-16')

----